---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-pvc"
  labels:
    app: "mongodb"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb"
spec:
  type: "NodePort"
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: "mongodb"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mongodb"
spec:
  selector:
    matchLabels:
      app: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
        - name: "mongodb"
          image: "mongo"
          imagePullPolicy: "Always"
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
            - name: "MONGO_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: "MONGO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
          ports:
            - containerPort: 27017
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-express"
spec:
  type: "NodePort"
  ports:
    - port: 8084
      targetPort: 8081
  selector:
    app: "mongo-express"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mongo-express"
spec:
  selector:
    matchLabels:
      app: "mongo-express"
  replicas: 1
  template:
    metadata:
      labels:
        app: "mongo-express"
    spec:
      containers:
        - name: "mongo-express"
          image: "mongo-express"
          imagePullPolicy: "Always"
          env:
            - name: "MONGO_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: "MONGO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
            - name: "ME_CONFIG_BASICAUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
            - name: "ME_CONFIG_MONGODB_ADMINUSERNAME"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: "ME_CONFIG_MONGODB_ADMINPASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
            - name: "ME_CONFIG_MONGODB_URL"
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: connectionstring
          ports:
            - containerPort: 8081
