apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: semesterproject
  labels:
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: registry.gitlab.sdu.dk/alnoe20/docker-images/dashboard:v5
          imagePullPolicy: "Always"
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENVIRONMENT
              value: "PRODUCTION"
            - name: MONGO_CONNECT
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: connectionstring
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dashboard"
spec:
  type: "NodePort"
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: "dashboard"
---

